/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILeaderboardRegistry,
  ILeaderboardRegistryInterface,
} from "../../ReactiveRewardEngine.sol/ILeaderboardRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_player",
        type: "address",
      },
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_description",
        type: "string",
      },
    ],
    name: "awardAchievement",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_player",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_points",
        type: "uint256",
      },
    ],
    name: "updateScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILeaderboardRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ILeaderboardRegistryInterface {
    return new Interface(_abi) as ILeaderboardRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILeaderboardRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ILeaderboardRegistry;
  }
}
