/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EventHandler {
  export type RuleSubscriptionStruct = {
    subscriptionId: BigNumberish;
    ruleId: BigNumberish;
    eventName: string;
    active: boolean;
  };

  export type RuleSubscriptionStructOutput = [
    subscriptionId: bigint,
    ruleId: bigint,
    eventName: string,
    active: boolean
  ] & {
    subscriptionId: bigint;
    ruleId: bigint;
    eventName: string;
    active: boolean;
  };
}

export interface EventHandlerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getSubscription"
      | "handleEventReaction"
      | "processEvent"
      | "processReactionPush"
      | "rewardEngine"
      | "subscribeToRule"
      | "subscriptionCounter"
      | "subscriptions"
      | "toggleSubscription"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ReactionProcessed"
      | "RuleExecuted"
      | "SubscriptionCreated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "handleEventReaction",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "processEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processReactionPush",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeToRule",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleSubscription",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleEventReaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processReactionPush",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribeToRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleSubscription",
    data: BytesLike
  ): Result;
}

export namespace ReactionProcessedEvent {
  export type InputTuple = [
    user: AddressLike,
    eventName: string,
    actionType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    eventName: string,
    actionType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    eventName: string;
    actionType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleExecutedEvent {
  export type InputTuple = [
    ruleId: BigNumberish,
    user: AddressLike,
    eventName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    ruleId: bigint,
    user: string,
    eventName: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    ruleId: bigint;
    user: string;
    eventName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    ruleId: BigNumberish,
    eventName: string
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    ruleId: bigint,
    eventName: string
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    ruleId: bigint;
    eventName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventHandler extends BaseContract {
  connect(runner?: ContractRunner | null): EventHandler;
  waitForDeployment(): Promise<this>;

  interface: EventHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getSubscription: TypedContractMethod<
    [_subscriptionId: BigNumberish],
    [EventHandler.RuleSubscriptionStructOutput],
    "view"
  >;

  handleEventReaction: TypedContractMethod<
    [_subscriptionId: BigNumberish, _user: AddressLike, _eventName: string],
    [void],
    "nonpayable"
  >;

  processEvent: TypedContractMethod<
    [_eventId: BigNumberish],
    [void],
    "nonpayable"
  >;

  processReactionPush: TypedContractMethod<
    [_user: AddressLike, _eventName: string],
    [void],
    "nonpayable"
  >;

  rewardEngine: TypedContractMethod<[], [string], "view">;

  subscribeToRule: TypedContractMethod<
    [_ruleId: BigNumberish, _eventName: string],
    [bigint],
    "nonpayable"
  >;

  subscriptionCounter: TypedContractMethod<[], [bigint], "view">;

  subscriptions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, boolean] & {
        subscriptionId: bigint;
        ruleId: bigint;
        eventName: string;
        active: boolean;
      }
    ],
    "view"
  >;

  toggleSubscription: TypedContractMethod<
    [_subscriptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [_subscriptionId: BigNumberish],
    [EventHandler.RuleSubscriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "handleEventReaction"
  ): TypedContractMethod<
    [_subscriptionId: BigNumberish, _user: AddressLike, _eventName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processEvent"
  ): TypedContractMethod<[_eventId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "processReactionPush"
  ): TypedContractMethod<
    [_user: AddressLike, _eventName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "subscribeToRule"
  ): TypedContractMethod<
    [_ruleId: BigNumberish, _eventName: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscriptionCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, boolean] & {
        subscriptionId: bigint;
        ruleId: bigint;
        eventName: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "toggleSubscription"
  ): TypedContractMethod<[_subscriptionId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ReactionProcessed"
  ): TypedContractEvent<
    ReactionProcessedEvent.InputTuple,
    ReactionProcessedEvent.OutputTuple,
    ReactionProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RuleExecuted"
  ): TypedContractEvent<
    RuleExecutedEvent.InputTuple,
    RuleExecutedEvent.OutputTuple,
    RuleExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;

  filters: {
    "ReactionProcessed(address,string,uint256,uint256)": TypedContractEvent<
      ReactionProcessedEvent.InputTuple,
      ReactionProcessedEvent.OutputTuple,
      ReactionProcessedEvent.OutputObject
    >;
    ReactionProcessed: TypedContractEvent<
      ReactionProcessedEvent.InputTuple,
      ReactionProcessedEvent.OutputTuple,
      ReactionProcessedEvent.OutputObject
    >;

    "RuleExecuted(uint256,address,string,uint256)": TypedContractEvent<
      RuleExecutedEvent.InputTuple,
      RuleExecutedEvent.OutputTuple,
      RuleExecutedEvent.OutputObject
    >;
    RuleExecuted: TypedContractEvent<
      RuleExecutedEvent.InputTuple,
      RuleExecutedEvent.OutputTuple,
      RuleExecutedEvent.OutputObject
    >;

    "SubscriptionCreated(uint256,uint256,string)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
  };
}
