/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LeaderboardRegistry {
  export type AchievementStruct = {
    id: BigNumberish;
    name: string;
    description: string;
    earnedBy: AddressLike;
    earnedAt: BigNumberish;
  };

  export type AchievementStructOutput = [
    id: bigint,
    name: string,
    description: string,
    earnedBy: string,
    earnedAt: bigint
  ] & {
    id: bigint;
    name: string;
    description: string;
    earnedBy: string;
    earnedAt: bigint;
  };

  export type PlayerStatsStruct = {
    playerAddress: AddressLike;
    score: BigNumberish;
    rank: BigNumberish;
    achievementCount: BigNumberish;
    lastScoreUpdate: BigNumberish;
    isActive: boolean;
  };

  export type PlayerStatsStructOutput = [
    playerAddress: string,
    score: bigint,
    rank: bigint,
    achievementCount: bigint,
    lastScoreUpdate: bigint,
    isActive: boolean
  ] & {
    playerAddress: string;
    score: bigint;
    rank: bigint;
    achievementCount: bigint;
    lastScoreUpdate: bigint;
    isActive: boolean;
  };
}

export interface LeaderboardRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "achievementCounter"
      | "achievements"
      | "admin"
      | "awardAchievement"
      | "getAchievement"
      | "getPlayerAchievements"
      | "getPlayerRank"
      | "getPlayerStats"
      | "getTopPlayers"
      | "playerAchievementIds"
      | "playerRank"
      | "playerStats"
      | "registerPlayer"
      | "rewardEngine"
      | "setRewardEngine"
      | "topPlayers"
      | "totalPlayers"
      | "updateScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AchievementAdded"
      | "LeaderboardUpdated"
      | "PlayerRegistered"
      | "RankUpdated"
      | "ScoreUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "achievementCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "achievements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "awardAchievement",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAchievement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerAchievements",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerRank",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopPlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerAchievementIds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerRank",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPlayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "topPlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateScore",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "achievementCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "achievements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "awardAchievement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAchievement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerAchievements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerAchievementIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "playerRank", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "topPlayers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateScore",
    data: BytesLike
  ): Result;
}

export namespace AchievementAddedEvent {
  export type InputTuple = [
    achievementId: BigNumberish,
    player: AddressLike,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    achievementId: bigint,
    player: string,
    name: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    achievementId: bigint;
    player: string;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaderboardUpdatedEvent {
  export type InputTuple = [
    totalPlayers: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [totalPlayers: bigint, timestamp: bigint];
  export interface OutputObject {
    totalPlayers: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerRegisteredEvent {
  export type InputTuple = [player: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [player: string, timestamp: bigint];
  export interface OutputObject {
    player: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RankUpdatedEvent {
  export type InputTuple = [
    player: AddressLike,
    newRank: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    newRank: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    player: string;
    newRank: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [
    player: AddressLike,
    newScore: BigNumberish,
    delta: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    newScore: bigint,
    delta: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    player: string;
    newScore: bigint;
    delta: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LeaderboardRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LeaderboardRegistry;
  waitForDeployment(): Promise<this>;

  interface: LeaderboardRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  achievementCounter: TypedContractMethod<[], [bigint], "view">;

  achievements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        name: string;
        description: string;
        earnedBy: string;
        earnedAt: bigint;
      }
    ],
    "view"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  awardAchievement: TypedContractMethod<
    [_player: AddressLike, _name: string, _description: string],
    [bigint],
    "nonpayable"
  >;

  getAchievement: TypedContractMethod<
    [_id: BigNumberish],
    [LeaderboardRegistry.AchievementStructOutput],
    "view"
  >;

  getPlayerAchievements: TypedContractMethod<
    [_player: AddressLike],
    [bigint[]],
    "view"
  >;

  getPlayerRank: TypedContractMethod<[_player: AddressLike], [bigint], "view">;

  getPlayerStats: TypedContractMethod<
    [_player: AddressLike],
    [LeaderboardRegistry.PlayerStatsStructOutput],
    "view"
  >;

  getTopPlayers: TypedContractMethod<
    [_limit: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;

  playerAchievementIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  playerRank: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  playerStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        playerAddress: string;
        score: bigint;
        rank: bigint;
        achievementCount: bigint;
        lastScoreUpdate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  registerPlayer: TypedContractMethod<
    [_player: AddressLike],
    [void],
    "nonpayable"
  >;

  rewardEngine: TypedContractMethod<[], [string], "view">;

  setRewardEngine: TypedContractMethod<
    [_engine: AddressLike],
    [void],
    "nonpayable"
  >;

  topPlayers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  totalPlayers: TypedContractMethod<[], [bigint], "view">;

  updateScore: TypedContractMethod<
    [_player: AddressLike, _points: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "achievementCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "achievements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        name: string;
        description: string;
        earnedBy: string;
        earnedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "awardAchievement"
  ): TypedContractMethod<
    [_player: AddressLike, _name: string, _description: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAchievement"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [LeaderboardRegistry.AchievementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerAchievements"
  ): TypedContractMethod<[_player: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPlayerRank"
  ): TypedContractMethod<[_player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [_player: AddressLike],
    [LeaderboardRegistry.PlayerStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopPlayers"
  ): TypedContractMethod<
    [_limit: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerAchievementIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerRank"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "playerStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        playerAddress: string;
        score: bigint;
        rank: bigint;
        achievementCount: bigint;
        lastScoreUpdate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerPlayer"
  ): TypedContractMethod<[_player: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setRewardEngine"
  ): TypedContractMethod<[_engine: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "topPlayers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalPlayers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateScore"
  ): TypedContractMethod<
    [_player: AddressLike, _points: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AchievementAdded"
  ): TypedContractEvent<
    AchievementAddedEvent.InputTuple,
    AchievementAddedEvent.OutputTuple,
    AchievementAddedEvent.OutputObject
  >;
  getEvent(
    key: "LeaderboardUpdated"
  ): TypedContractEvent<
    LeaderboardUpdatedEvent.InputTuple,
    LeaderboardUpdatedEvent.OutputTuple,
    LeaderboardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerRegistered"
  ): TypedContractEvent<
    PlayerRegisteredEvent.InputTuple,
    PlayerRegisteredEvent.OutputTuple,
    PlayerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RankUpdated"
  ): TypedContractEvent<
    RankUpdatedEvent.InputTuple,
    RankUpdatedEvent.OutputTuple,
    RankUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;

  filters: {
    "AchievementAdded(uint256,address,string,uint256)": TypedContractEvent<
      AchievementAddedEvent.InputTuple,
      AchievementAddedEvent.OutputTuple,
      AchievementAddedEvent.OutputObject
    >;
    AchievementAdded: TypedContractEvent<
      AchievementAddedEvent.InputTuple,
      AchievementAddedEvent.OutputTuple,
      AchievementAddedEvent.OutputObject
    >;

    "LeaderboardUpdated(uint256,uint256)": TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;
    LeaderboardUpdated: TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;

    "PlayerRegistered(address,uint256)": TypedContractEvent<
      PlayerRegisteredEvent.InputTuple,
      PlayerRegisteredEvent.OutputTuple,
      PlayerRegisteredEvent.OutputObject
    >;
    PlayerRegistered: TypedContractEvent<
      PlayerRegisteredEvent.InputTuple,
      PlayerRegisteredEvent.OutputTuple,
      PlayerRegisteredEvent.OutputObject
    >;

    "RankUpdated(address,uint256,uint256)": TypedContractEvent<
      RankUpdatedEvent.InputTuple,
      RankUpdatedEvent.OutputTuple,
      RankUpdatedEvent.OutputObject
    >;
    RankUpdated: TypedContractEvent<
      RankUpdatedEvent.InputTuple,
      RankUpdatedEvent.OutputTuple,
      RankUpdatedEvent.OutputObject
    >;

    "ScoreUpdated(address,uint256,int256,uint256)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
  };
}
