/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ReactiveRewardEngine {
  export type EventStruct = {
    id: BigNumberish;
    user: AddressLike;
    eventName: string;
    metadata: string;
    timestamp: BigNumberish;
    processed: boolean;
  };

  export type EventStructOutput = [
    id: bigint,
    user: string,
    eventName: string,
    metadata: string,
    timestamp: bigint,
    processed: boolean
  ] & {
    id: bigint;
    user: string;
    eventName: string;
    metadata: string;
    timestamp: bigint;
    processed: boolean;
  };

  export type RuleStruct = {
    id: BigNumberish;
    eventName: string;
    condition: string;
    actionType: BigNumberish;
    rewardAmount: BigNumberish;
    badgeName: string;
    badgeMetadata: string;
    owner: AddressLike;
    isActive: boolean;
    createdAt: BigNumberish;
  };

  export type RuleStructOutput = [
    id: bigint,
    eventName: string,
    condition: string,
    actionType: bigint,
    rewardAmount: bigint,
    badgeName: string,
    badgeMetadata: string,
    owner: string,
    isActive: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    eventName: string;
    condition: string;
    actionType: bigint;
    rewardAmount: bigint;
    badgeName: string;
    badgeMetadata: string;
    owner: string;
    isActive: boolean;
    createdAt: bigint;
  };
}

export interface ReactiveRewardEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "emitCustomEvent"
      | "eventHandler"
      | "events"
      | "executeAction"
      | "getEvent"
      | "getEventCounter"
      | "getEventTuple"
      | "getRule"
      | "getRuleCounter"
      | "getUserAchievements"
      | "getUserRewards"
      | "registerRule"
      | "rules"
      | "setEventHandler"
      | "toggleRule"
      | "userAchievements"
      | "userRewardBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AchievementUnlocked"
      | "EventTriggered"
      | "RewardMinted"
      | "RuleRegistered"
      | "ScoreUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emitCustomEvent",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "eventHandler",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "events",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEventTuple",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRuleCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAchievements",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRule",
    values: [string, string, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(functionFragment: "rules", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "setEventHandler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleRule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userAchievements",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userRewardBalance",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emitCustomEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "events", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEventCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventTuple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRuleCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAchievements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEventHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "toggleRule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userAchievements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRewardBalance",
    data: BytesLike
  ): Result;
}

export namespace AchievementUnlockedEvent {
  export type InputTuple = [
    user: AddressLike,
    badgeId: BigNumberish,
    badgeName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    badgeId: bigint,
    badgeName: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    badgeId: bigint;
    badgeName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventTriggeredEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    user: AddressLike,
    eventName: string,
    metadata: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    user: string,
    eventName: string,
    metadata: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    user: string;
    eventName: string;
    metadata: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardMintedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleRegisteredEvent {
  export type InputTuple = [
    ruleId: BigNumberish,
    owner: AddressLike,
    eventName: string,
    rewardAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    ruleId: bigint,
    owner: string,
    eventName: string,
    rewardAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    ruleId: bigint;
    owner: string;
    eventName: string;
    rewardAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    newScore: BigNumberish,
    delta: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    newScore: bigint,
    delta: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    newScore: bigint;
    delta: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReactiveRewardEngine extends BaseContract {
  connect(runner?: ContractRunner | null): ReactiveRewardEngine;
  waitForDeployment(): Promise<this>;

  interface: ReactiveRewardEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  emitCustomEvent: TypedContractMethod<
    [_eventName: string, _metadata: string],
    [void],
    "nonpayable"
  >;

  eventHandler: TypedContractMethod<[], [string], "view">;

  events: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean] & {
        id: bigint;
        user: string;
        eventName: string;
        metadata: string;
        timestamp: bigint;
        processed: boolean;
      }
    ],
    "view"
  >;

  executeAction: TypedContractMethod<
    [_user: AddressLike, _ruleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent: TypedContractMethod<
    [_eventId: BigNumberish],
    [ReactiveRewardEngine.EventStructOutput],
    "view"
  >;

  getEventCounter: TypedContractMethod<[], [bigint], "view">;

  getEventTuple: TypedContractMethod<
    [_eventId: BigNumberish],
    [[string, string, string, bigint, boolean]],
    "view"
  >;

  getRule: TypedContractMethod<
    [_ruleId: BigNumberish],
    [ReactiveRewardEngine.RuleStructOutput],
    "view"
  >;

  getRuleCounter: TypedContractMethod<[], [bigint], "view">;

  getUserAchievements: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserRewards: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  registerRule: TypedContractMethod<
    [
      _eventName: string,
      _condition: string,
      _actionType: BigNumberish,
      _rewardAmount: BigNumberish,
      _badgeName: string,
      _badgeMetadata: string
    ],
    [bigint],
    "nonpayable"
  >;

  rules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        boolean,
        bigint
      ] & {
        id: bigint;
        eventName: string;
        condition: string;
        actionType: bigint;
        rewardAmount: bigint;
        badgeName: string;
        badgeMetadata: string;
        owner: string;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  setEventHandler: TypedContractMethod<
    [_handler: AddressLike],
    [void],
    "nonpayable"
  >;

  toggleRule: TypedContractMethod<
    [_ruleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userAchievements: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userRewardBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emitCustomEvent"
  ): TypedContractMethod<
    [_eventName: string, _metadata: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eventHandler"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "events"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean] & {
        id: bigint;
        user: string;
        eventName: string;
        metadata: string;
        timestamp: bigint;
        processed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeAction"
  ): TypedContractMethod<
    [_user: AddressLike, _ruleId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEvent"
  ): TypedContractMethod<
    [_eventId: BigNumberish],
    [ReactiveRewardEngine.EventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEventCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEventTuple"
  ): TypedContractMethod<
    [_eventId: BigNumberish],
    [[string, string, string, bigint, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRule"
  ): TypedContractMethod<
    [_ruleId: BigNumberish],
    [ReactiveRewardEngine.RuleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRuleCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserAchievements"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserRewards"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerRule"
  ): TypedContractMethod<
    [
      _eventName: string,
      _condition: string,
      _actionType: BigNumberish,
      _rewardAmount: BigNumberish,
      _badgeName: string,
      _badgeMetadata: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        boolean,
        bigint
      ] & {
        id: bigint;
        eventName: string;
        condition: string;
        actionType: bigint;
        rewardAmount: bigint;
        badgeName: string;
        badgeMetadata: string;
        owner: string;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setEventHandler"
  ): TypedContractMethod<[_handler: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleRule"
  ): TypedContractMethod<[_ruleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userAchievements"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userRewardBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "AchievementUnlocked"
  ): TypedContractEvent<
    AchievementUnlockedEvent.InputTuple,
    AchievementUnlockedEvent.OutputTuple,
    AchievementUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "EventTriggered"
  ): TypedContractEvent<
    EventTriggeredEvent.InputTuple,
    EventTriggeredEvent.OutputTuple,
    EventTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "RewardMinted"
  ): TypedContractEvent<
    RewardMintedEvent.InputTuple,
    RewardMintedEvent.OutputTuple,
    RewardMintedEvent.OutputObject
  >;
  getEvent(
    key: "RuleRegistered"
  ): TypedContractEvent<
    RuleRegisteredEvent.InputTuple,
    RuleRegisteredEvent.OutputTuple,
    RuleRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;

  filters: {
    "AchievementUnlocked(address,uint256,string,uint256)": TypedContractEvent<
      AchievementUnlockedEvent.InputTuple,
      AchievementUnlockedEvent.OutputTuple,
      AchievementUnlockedEvent.OutputObject
    >;
    AchievementUnlocked: TypedContractEvent<
      AchievementUnlockedEvent.InputTuple,
      AchievementUnlockedEvent.OutputTuple,
      AchievementUnlockedEvent.OutputObject
    >;

    "EventTriggered(uint256,address,string,string,uint256)": TypedContractEvent<
      EventTriggeredEvent.InputTuple,
      EventTriggeredEvent.OutputTuple,
      EventTriggeredEvent.OutputObject
    >;
    EventTriggered: TypedContractEvent<
      EventTriggeredEvent.InputTuple,
      EventTriggeredEvent.OutputTuple,
      EventTriggeredEvent.OutputObject
    >;

    "RewardMinted(address,uint256,string,uint256)": TypedContractEvent<
      RewardMintedEvent.InputTuple,
      RewardMintedEvent.OutputTuple,
      RewardMintedEvent.OutputObject
    >;
    RewardMinted: TypedContractEvent<
      RewardMintedEvent.InputTuple,
      RewardMintedEvent.OutputTuple,
      RewardMintedEvent.OutputObject
    >;

    "RuleRegistered(uint256,address,string,uint256,uint256)": TypedContractEvent<
      RuleRegisteredEvent.InputTuple,
      RuleRegisteredEvent.OutputTuple,
      RuleRegisteredEvent.OutputObject
    >;
    RuleRegistered: TypedContractEvent<
      RuleRegisteredEvent.InputTuple,
      RuleRegisteredEvent.OutputTuple,
      RuleRegisteredEvent.OutputObject
    >;

    "ScoreUpdated(address,uint256,int256,uint256)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
  };
}
